# Generated by Django 2.2.4 on 2021-02-23 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restful_tv_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TVShows',
            new_name='TVShow',
        ),
    ]
