# Generated by Django 2.2.4 on 2021-02-23 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restful_tv_app', '0002_auto_20210222_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvshow',
            old_name='network',
            new_name='networks',
        ),
    ]
